/*
 * SimAnt (SNES, Maxis / Imagineer / Tomcat Systems, 1993)
 *
 * Structural C reconstruction lifted from the 65816 disassembly. NOT a
 * runnable port — every ROM-side detail that hasn't been lifted yet is
 * a stub. What's modeled here:
 *
 *   - The complete boot path RESET → main_9340 → sub_BB8D → sub_896D.
 *   - The NMI handler and every per-frame helper it calls.
 *   - The cooperative task switcher built into the NMI tail.
 *   - The game-state pipeline (10 named states in $0B + dispatch table).
 *   - The entity system: 20-byte records, per-type init tables, dispatch
 *     through a 32-entry table at $04:9A30, per-state machines via byte 1.
 *   - The SPC700 sound-driver upload at $08:8006.
 *   - The VRAM/asset path: decompress to $7E:2000 → DMA into VRAM.
 *   - The 3-byte SRAM signature at $70:7FA0-A2 and bulk save at $70:0000.
 *   - The vblank-sync routine that handles SELECT (toggle view) and the
 *     joypad shadow reads used by sub_8101 (pause toggle).
 *
 * Manual-derived names come from the recovered ASCII strings (see
 * `strings.py`/`dig.py`) and the SimAnt instruction booklet vocabulary
 * (Yellow Ant, Black/Red colony, castes, scenarios, evaluation screens).
 *
 * File companions:
 *   disasm.txt — RESET, NMI, key subroutines (regenerated by disasm.py)
 *   dig.txt    — entity handler prologues, state handlers, HW scans,
 *                decompressor/save-game/SPC700-uploader call sites
 */

#include <stdint.h>

/* ========================================================================
 * MEMORY MODEL
 * ========================================================================
 *
 * SNES WRAM is 128 KB. Banks $7E and $7F map to it directly. Banks
 * $00-$3F at addresses $0000-$1FFF mirror $7E:0000-$7E:1FFF, which is
 * where most of the lifted code reads/writes. The direct-page register
 * is pinned at $0000 during NMI and during main_9340, so dp[i] is just
 * an alias for wram[i].
 *
 * Bank $70 in LoROM ($70:0000-$70:7FFF) is the 32 KB battery SRAM
 * declared in the cart header.
 */
static uint8_t  wram[0x20000];    /* $7E:0000 .. $7F:FFFF                  */
static uint8_t  sram[0x08000];    /* $70:0000 .. $70:7FFF                  */
#define dp wram                   /* direct page = wram[0..0xFF]           */

static volatile uint8_t  mmio[0x10000];
#define MMIO8(addr)  (*(volatile uint8_t *)&mmio[(addr) & 0xFFFF])
#define MMIO16(addr) (*(volatile uint16_t*)&mmio[(addr) & 0xFFFF])

/* SNES MMIO names actually touched by lifted code. */
#define INIDISP    MMIO8 (0x2100)
#define VMADDL     MMIO16(0x2116)
#define VMDATAL    MMIO8 (0x2118)
#define BG1HOFS    MMIO8 (0x210D)
#define BG1VOFS    MMIO8 (0x210E)
#define BG2HOFS    MMIO8 (0x210F)
#define BG2VOFS    MMIO8 (0x2110)
#define BG3HOFS    MMIO8 (0x2111)
#define BG3VOFS    MMIO8 (0x2112)
#define APUIO0     MMIO8 (0x2140)
#define APUIO1     MMIO8 (0x2141)
#define APUIO2     MMIO8 (0x2142)
#define APUIO3     MMIO8 (0x2143)
#define NMITIMEN   MMIO8 (0x4200)
#define RDNMI      MMIO8 (0x4210)
#define MDMAEN     MMIO8 (0x420B)
#define HDMAEN     MMIO8 (0x420C)
#define JOY1L      MMIO8 (0x4218)
#define JOY1H      MMIO8 (0x4219)
#define JOY2L      MMIO8 (0x421A)
#define JOY2H      MMIO8 (0x421B)
/* DMA channel 0. */
#define DMA0_PARAM MMIO8 (0x4300)
#define DMA0_DEST  MMIO8 (0x4301)
#define DMA0_SRC   MMIO16(0x4302)
#define DMA0_BANK  MMIO8 (0x4304)
#define DMA0_LEN   MMIO16(0x4305)

/* JOY1 bit masks (SNES Mouse maps left → A, right → B). */
#define BTN_R       0x0010
#define BTN_L       0x0020
#define BTN_X       0x0040
#define BTN_A       0x0080
#define BTN_RIGHT   0x0100
#define BTN_LEFT    0x0200
#define BTN_DOWN    0x0400
#define BTN_UP      0x0800
#define BTN_START   0x1000
#define BTN_SELECT  0x2000
#define BTN_Y       0x4000
#define BTN_B       0x8000

/* ========================================================================
 * DIRECT-PAGE LAYOUT (what the lifted code actually uses)
 * ========================================================================
 *
 * $00..$04   wall clock (also: $00 = current cooperative task index)
 * $02        reused: at boot it's the task-count limit; during gameplay
 *            it's clock-seconds. Safe because the task count is set to 2
 *            at boot and only ever incremented by spawn_task (which runs
 *            before the clock starts).
 * $05..$09   spawn_task scratch (A=$05, X=$06.07, saved SP=$08.09)
 * $0A        $4200/NMITIMEN value ($81 = NMI + joypad auto-read)
 * $0A..$31   per-task scheduler tables (see SCHEDULER section below)
 * $0B        GAME STATE — index into the dispatch table at $9369
 * $0C..$11   "marker positions" — 6 bytes used by entity types 3/4/5
 *            to compute on-screen draw coordinates
 * $21        ?
 * $26        view mode (zeroed when SELECT toggles view)
 * $2A        pause flag (set by START; sub_8101)
 * $2C..$2D   VRAM update queue length, in bytes (queue at $0C00)
 * $2E..$2F   OAM index (sub_8937 zeros it)
 * $30..$31   entity-table end pointer (bytes used since $04:0600)
 * $32..$33   OAM allocator: next-free hi-priority slot ($0010 at boot)
 * $34..$35   OAM allocator: next-free lo-priority slot ($0110 at boot)
 * $37..$3E   draw helpers' scratch: $37/$38 = X, $39/$3A = Y, $3B/$3C =
 *            tile index, $3D = attribute
 * $44..$4F   misc game-state vars seeded in sub_BB8D
 * $46..$51   BG1/BG2/BG3 H+V scroll shadows (sub_884A pushes them)
 * $55        misc
 * $57..$58   "BG row changed?" guard for sub_8553
 * $5B        sub_85B2 state-machine guard (bails when >= 4)
 * $60..$61   joypad PREVIOUS-FRAME shadows (just-pressed edge detection)
 * $64        misc
 * $6C        screen-fade counter (used by $00:8616 fade loop)
 * $71        "lockout pause / SELECT" flag (set while a menu is open)
 * $73        misc
 * $81        ?
 * $82..$83   "indirect handler address" — set by sub_049966 before each
 *            entity-handler dispatch
 * $88        VRAM stream cursor (selects which of 8 fixed blocks to
 *            upload this frame; jump table at $815A)
 * $89        misc
 * $8C        misc
 * $E7..$E9   24-bit source pointer used by the SPC700 uploader
 *
 * Bigger pages:
 *   $0160/$0161  joypad CURRENT-FRAME shadows (JOY1L / JOY1H)
 *   $0200..$02FF reserved for menus / dialogs (some bytes seeded in
 *                sub_BB8D)
 *   $02B9/$02BA  16-bit pulse counter (incremented once every time the
 *                free-running tick wraps past 4 — roughly every 256
 *                frames)
 *   $02CF/$02D0  decompressor source pointer
 *   $02D1        decompressor "count" parameter (passed via A by $8D7E)
 *   $02D4/$02D5  decompressor dest address (set to $2000 by $8D7E)
 *   $02D6        decompressor dest bank   (set to $7E by $8D7E)
 *
 * Persistent SRAM scratch shadow at $7F:E710..$7F:E719 (purpose TBD).
 */

/* ========================================================================
 * GAME STATES — dp[$0B] indexes into the 10-entry table at $00:9369.
 * Each handler RUNS-ONCE: sets up its screen, then does INC dp[$0B] so the
 * NEXT frame the dispatcher picks up the following state.
 * ========================================================================
 *
 *   GS_FULL_GAME        $00:ACF3   silence APU, load FULL-game palette+map
 *   GS_SCENARIO_GAME    $00:AD5B   spawn 4 tasks via $877D, wait for count
 *                                  to hit 4, then fade out and advance
 *   GS_SAVED_GAME       $00:AC63   load SAVED-game menu palette+map
 *   GS_TUTORIAL         $00:ACE8   trivial: JSR $BA9E($04), $8616, INC
 *   GS_ANT_INFORMATION  $00:B155   silence APU, load encyclopedia screen
 *                                  (calls JSL $08:8003 to decompress)
 *   GS_MARRIAGE_FLIGHT  $00:B18C   the breeders' mating-flight screen
 *                                  (the manual ties this to pop>=100 +
 *                                  20 breeders — see p.19 "Expanding")
 *   GS_FULL_END         $00:B07B   FULL Game victory screen (3 asset loads)
 *   GS_SCENARIO_END     $00:B0FC   per-scenario victory screen; long JSL
 *                                  chain to $04:99BB / $04:99C1 to spawn
 *                                  the celebration entities
 *   GS_GAME_OVER        $00:B19F   force-blank, spawn type-$5E entity,
 *                                  re-enable NMI, advance
 *   GS_SOUND            $00:B1BF   Sound options screen ($BA9E + $BACA)
 * ----------------------------------------------------------------------- */
enum GameState {
    GS_FULL_GAME       = 0, GS_SCENARIO_GAME   = 1, GS_SAVED_GAME    = 2,
    GS_TUTORIAL        = 3, GS_ANT_INFORMATION = 4, GS_MARRIAGE_FLIGHT=5,
    GS_FULL_END        = 6, GS_SCENARIO_END    = 7, GS_GAME_OVER     = 8,
    GS_SOUND           = 9,
    /* Beyond 9 are runtime gameplay states. Save game lands at $1A
     * (see $00:959D: STA #$1A / $0B / RTS). */
    GS_AFTER_SAVE      = 0x1A,
};

/* Scenarios (manual p.22-23). The strings only appear at runtime as
 * "SCENARIO GAME LEVEL n" so these come from the manual. */
enum ScenarioLevel {
    SL_PARK = 1, SL_GARDEN, SL_RAINY_YARD, SL_HOUSE,
    SL_ROAD,     SL_RIVER,  SL_PORCH,      SL_WOODS,
};

/* Views: see strings at $0187xx. */
enum ViewMode {
    VIEW_SURFACE_OVERVIEW = 0, VIEW_B_NEST_OVERVIEW = 1,
    VIEW_R_NEST_OVERVIEW  = 2, VIEW_SURFACE_CLOSEUP = 3,
    VIEW_B_NEST_CLOSEUP   = 4, VIEW_R_NEST_CLOSEUP  = 5,
};

enum ScentDisplay {
    SCENT_HIDE = 0, SCENT_BLACK_NEST = 1, SCENT_RED_NEST = 2,
    SCENT_BLACK_TRAIL = 3, SCENT_RED_TRAIL = 4,
};

enum Caste    { CASTE_WORKER = 0, CASTE_SOLDIER = 1, CASTE_BREEDER = 2 };
enum Behavior { BHV_FORAGE   = 0, BHV_DIG       = 1, BHV_NURSE    = 2 };

enum RecruitChoice {
    RECRUIT_5    = 0, RECRUIT_10  = 1, RECRUIT_ALL = 2,
    RELEASE_HALF = 3, RELEASE_ALL = 4,
};

/* ========================================================================
 * ENTITY SYSTEM — 32 types, 20-byte records, per-type per-state machines.
 * ========================================================================
 *
 * Layout decoded from spawn helper $04:99C1 and the per-handler prologues
 * (most handlers do `TXY / LDA $0001,x / ASL / TAX / JMP (table)` — i.e.
 * they switch on byte +1).
 *
 *   +0   type            (1 byte; index into entity_handlers[])
 *   +1   state           (1 byte; per-type state-machine index)
 *   +2-3 x position      (2 bytes, 16-bit)
 *   +4-5 y position      (2 bytes)
 *   +6   flag            (1 byte; spawn zeroes it)
 *   +7-B scratch         (5 bytes; per-handler use)
 *   +C-D init constant   (2 bytes; copied at spawn from table $01:EF59)
 *   +E   zero            (spawn-time)
 *   +F   init attribute  (1 byte; copied from $01:F043 — looks like an
 *                         OAM-style priority+palette byte for sprite types)
 *   +10  zero            (spawn-time)
 *   +11-13 trailing scratch
 *
 * Handler dispatch:
 *   sub_049966 in bank $04 walks the table at $04:0600 from X=$0600 until
 *   X >= dp[$30]. For each entity whose type != 0, it tail-calls the
 *   handler in the 32-entry table at $04:9A30. Empty slots have type=0;
 *   no special "dead" marker needed.
 *
 * Aliases:
 *   type 19 == 18 ($04:A533) — likely "queen" variants share AI
 *   type 21 == 16 ($04:A356)
 *   type 22 == 10 ($04:9E9C) — likely B/R variant share
 *
 * Heuristic role guesses (LIFT EACH HANDLER TO CONFIRM):
 *   type  0:  empty slot                        — handler is `RTS`
 *   type  1:  cursor / input pickup             — handler reads dp[$60/$61]
 *                                                 (JOY1 prev) for A & B
 *   type  2:  some menu/screen polled element   — checks dp[$004E] sign
 *   type  3:  selection-rectangle marker        — draws at dp[$0C/$0D]
 *   type  4:  marker variant                    — draws at dp[$0E/$0F]
 *   type  5:  marker variant                    — draws at dp[$10/$11]
 *   type  6:  countdown-driven object           — checks $02B2 vs $024A
 *   type  7:  static UI prop at dp[$0E/$0F]
 *   type  8:  static UI prop at dp[$10/$11]
 *   types 9-22: creatures (ants / spider / ant lion / caterpillar) —
 *               all use the per-state JMP table pattern
 *   type 18/19: Queen Ant (Black + Red variants alias to same handler)
 *   type 26:    "recruit ring" or particle generator (spawns sprites in a
 *               grid stepping +$40 in X and Y; see $04:AB0B)
 *   type 29:    pop-up dialog gate (checks dp[$02A7])
 *   type 31:    menu gate (checks dp[$0200])
 *
 * The MAP from manual characters to type IDs needs lifting the handler
 * bodies, not just prologues — what each one DOES in state 0 vs state 1
 * etc. is what distinguishes Worker from Soldier from Spider.
 * ----------------------------------------------------------------------- */
typedef struct __attribute__((packed)) Entity {
    uint8_t  type;         /* +0   */
    uint8_t  state;        /* +1   per-type state-machine index */
    uint16_t x;            /* +2-3 */
    uint16_t y;            /* +4-5 */
    uint8_t  flag;         /* +6   */
    uint8_t  scratch[5];   /* +7-B */
    uint16_t init_word;    /* +C-D  from table $01:EF59[type] */
    uint8_t  pad_e;        /* +E   */
    uint8_t  init_attr;    /* +F   from table $01:F043[type] */
    uint8_t  pad_10;       /* +10  */
    uint8_t  tail[3];      /* +11-13 */
} Entity;
_Static_assert(sizeof(Entity) == 20, "entity record is 20 bytes");

/* In WRAM: entity table at $04:0600 == wram[0x0600] (LoROM mirror). */
#define ENTITY_TABLE   ((Entity *)&wram[0x0600])
#define ENTITY_END     (*(uint16_t *)&dp[0x30])  /* end offset, in bytes */

/* Per-type initialization tables in ROM bank $01. */
extern const uint16_t entity_init_word[32];     /* $01:EF59 */
extern const uint8_t  entity_init_attr[32];     /* $01:F043 */

/* Handler signature — called with X pointing at the entity by the original
 * code, with DBR = $04. */
typedef void (*EntityHandler)(Entity *self);
extern EntityHandler entity_handlers[32];       /* $04:9A30 */

/* ========================================================================
 * COOPERATIVE TASK SCHEDULER
 * ========================================================================
 *
 * Task table arrays are interleaved through dp:
 *   dp[$0A + 2i]  saved SP for task i
 *   dp[$12 + 2i]  reload countdown
 *   dp[$1A + 2i]  current countdown
 *   dp[$22 + 2i]  enable flag (non-zero = scheduleable)
 * Up to 8 tasks. dp[$02] holds the in-use limit in bytes (2 * task_count).
 *
 * The NMI tail saves the interrupted task's SP at dp[$0A + 2*CUR_TASK],
 * advances to the next slot (mod limit), and for each:
 *   - if enabled, decrement its countdown
 *   - if countdown reaches 0, reload it, switch SP to that task, RTI
 *   - if countdown stays > 0, that task waits another frame; move on
 *
 * Effect: RTI pops PC and status from whatever stack we switched to, so
 * each task runs on its own stack page ($03xx, $04xx, ...). Tasks are
 * "preempted" only by NMI; between NMIs each task runs without
 * interruption.
 * ----------------------------------------------------------------------- */
#define CUR_TASK        dp[0x00]
#define TASK_LIMIT      dp[0x02]
#define TASK_SP(i)      (*(uint16_t *)&dp[0x0A + 2*(i)])
#define TASK_RELOAD(i)  (*(uint16_t *)&dp[0x12 + 2*(i)])
#define TASK_COUNT(i)   (*(uint16_t *)&dp[0x1A + 2*(i)])
#define TASK_ENABLE(i)  (*(uint16_t *)&dp[0x22 + 2*(i)])

/* spawn_task ($00:8113) — push a synthetic interrupt frame onto a fresh
 * stack page so the scheduler's eventual RTI lands at `pc` with the
 * standard register set restored. Verified asm:
 *
 *   STA $05 / STX $06          ; preserve A and X (PC)
 *   TSX / STX $08              ; preserve caller SP
 *   LDA $02 / LSR / CLC / ADC #$03  ; task_count + 3
 *   XBA / LDA #$FF / TCS       ; SP = ((task_count+3) << 8) | $FF
 *                              ; -> task 0 SP=$03FF, task 1 SP=$04FF, etc.
 *   LDA $05 / PHA              ; push 1 byte → PBR (= the A param)
 *   LDX $06 / PHX              ; push 2 bytes → PC (= the X param)
 *   PHP                        ; push 1 byte → P (status)
 *   PHX / PHX / PHX            ; push 3 × 2 bytes → initial X, Y, A
 *   PHB                        ; push 1 byte → initial B (data bank)
 *   LDA $02 / LSR / XBA / LDA #$00 / TAX / PHX
 *                              ; push 2 bytes → initial D (= task_count<<8)
 *   LDY $02 / TSX / STX $0A,y  ; save the new SP at dp[$0A+task_idx*2]
 *   LDA #$01
 *     STA $0012,y              ; reload = 1 (8-bit; high byte stays 0)
 *     STA $001A,y              ; count  = 1
 *     STA $0022,y              ; enable = 1
 *   INY / INY / STY $02        ; task_limit += 2
 *   LDX $08 / TXS / RTS        ; restore caller SP, return
 *
 * Stack frame for the scheduler's RTI sequence (bottom of stack → top):
 *   PBR (caller A) / PC (caller X) / P / X / Y / A / B / D
 *
 * The C model below ONLY updates the scheduler bookkeeping fields. The
 * synthetic stack frame is host-irrelevant — for a real port, replace
 * with setjmp/coroutine setup that resumes at `pc` with `a` in A. */
static void spawn_task(uint16_t pc, uint8_t a)
{
    unsigned slot = TASK_LIMIT >> 1;
    (void)pc; (void)a;
    TASK_RELOAD(slot) = 1;
    TASK_COUNT (slot) = 1;
    TASK_ENABLE(slot) = 1;
    TASK_LIMIT += 2;
}

/* The actual SP-swap-and-RTI step. Faithful C is impossible without
 * coroutines or setjmp/longjmp gymnastics — this is documentation. */
static void scheduler_switch_and_rti(void)
{
    /* see $00:80D0 .. $00:8100 in disasm.txt */
}

/* ========================================================================
 * RESET — $00:8009 (emulation-mode entry)
 * ======================================================================== */
static void main_9340(void);

void reset(void)
{
    /* SEI, CLD, CLC+XCE => native mode. DBR=0, D=0. */
    MDMAEN = 0;
    HDMAEN = 0;
    for (unsigned i = 0; i < 0x2000; ++i) wram[i] = 0;
    /* SP = $03FF. JMP $9340. */
    main_9340();
}

/* ========================================================================
 * main_9340 — task 0's body. Spawns task 1, calls boot inits, idles.
 * ======================================================================== */
static void boot_init_BB8D(void);
static void enable_nmi_896D(void);

/* See wiki/01-architecture.md "Game State Machine" section — 68-entry
 * dispatch at $00:9369, dp[$0B] is the state byte. Each handler is
 * run-once and INCs dp[$0B] to advance. */
static void game_state_dispatch_935C(void)
{
    /* Task 1 entry. Real handler table is at $9369 in ROM. */
    static void (* const dispatch[10])(void);
    for (;;) {
        unsigned s = dp[0x0B];
        if (s < 10 && dispatch[s])
            dispatch[s]();
    }
}

/* See wiki/01-architecture.md "main_9340" section */
static void main_9340(void)
{
    /* Asm @ $00:9340:
     *   LDY #$0002 / STY $02          ; TASK_LIMIT = 2 (one task already)
     *   LDA #$00 / LDX #$935C
     *   JSR $8113                      ; spawn_task(pc=$935C, a=$00)
     *   LDA #$01 / XBA / LDA #$00 / TCD   ; D := $0100  (NOT $0001)
     *   CLI                            ; unmask IRQs (defensive)
     *   JSR $BB8D                      ; boot_init
     *   JSR $896D                      ; enable_nmi
     *   BRA $935A                      ; spin forever; NMI scheduler yanks
     *                                  ;   us between this and task 1.
     *
     * The TCD sequence loads A=$0100 (A_hi=1, A_lo=0) then transfers to
     * D. Direct page = $0100 means all `LDA $xx` ZP loads in this task
     * read from $0100+xx, not $0000+xx. Important: the NMI handler
     * explicitly sets D=$0000 on entry, so dp[] semantics in the NMI
     * still target the bank-0 page. */
    TASK_LIMIT = 2;
    spawn_task(/*pc=*/0x935C, /*a=*/0x00);

    /* main task's direct page is $0100, not 0 — host-irrelevant since
     * the simulation uses absolute addressing for everything. */
    boot_init_BB8D();
    enable_nmi_896D();

    for (;;) ;
}

/* ========================================================================
 * NMI handler — vector points to $00:803E
 * ======================================================================== */
static void vram_stream_step_814F(void);
static void per_frame_even_8553(void);
static void per_frame_odd_85B2(void);
static void vram_queue_flush_C804(void);
static void oam_index_reset_8937(void);
static void bg_scroll_push_884A(void);
static void shadow_oam_clear_88A5(void);
static void entity_step_all_049966(void);
static void pause_toggle_on_start_8101(void);

/* See wiki/01-architecture.md "NMI handler" section — per-frame pipeline,
 * scheduler SP-swap, wall clock at dp[$00..$04].
 *
 * See wiki/16-rendering-pipeline.md for the full NMI rendering pipeline:
 * shadow-OAM DMA, VRAM streamer (sub_814F + jump table $815A), VRAM
 * update queue ($00:0C00 / sub_C804), CGRAM trickle flush, BG scroll
 * push, shadow-OAM clear (sprite parking at Y=$E0), and the per-view
 * tile/palette tables at $01:996F / $9A5F. */
void nmi(void)
{
    (void)RDNMI;                              /* acknowledge */

    /* Shadow OAM DMA: 0x220 bytes from $00:0D00 -> $2104. */
    DMA0_PARAM = 0x00;
    DMA0_DEST  = 0x04;                        /* $2104 = OAMDATA */
    DMA0_SRC   = 0x0D00;
    DMA0_BANK  = 0x00;
    DMA0_LEN   = 0x0220;
    MDMAEN     = 0x01;

    vram_stream_step_814F();
    if ((CUR_TASK & 1) == 0) per_frame_even_8553();
    else                     per_frame_odd_85B2();

    vram_queue_flush_C804();
    oam_index_reset_8937();
    bg_scroll_push_884A();
    shadow_oam_clear_88A5();
    entity_step_all_049966();
    pause_toggle_on_start_8101();

    /* Wall clock at dp[$00..$04]. dp[$00] is also the cooperative-task ID. */
    dp[0x00]++;
    if (++dp[0x01] >= 60) {
        dp[0x01] = 0;
        if (++dp[0x02] >= 60) {
            dp[0x02] = 0;
            if (++dp[0x03] >= 60) {
                dp[0x03] = 0;
                dp[0x04]++;
            }
        }
    }

    /* Once every 256 frames (when CUR_TASK rolls past 4): bump the
     * long-tick counter at dp[$02B9..$02BA]. */
    if (dp[0x00] == 4) (*(uint16_t *)&wram[0x02B9])++;

    scheduler_switch_and_rti();               /* SP-swap + RTI */
}

/* ========================================================================
 * Per-frame NMI helpers
 * ======================================================================== */

/* sub_814F — VRAM streamer. Indexes a jump table at $815A by 2*dp[$88];
 * each entry sets up a DMA from a fixed source in WRAM to a fixed VRAM
 * destination. dp[$88] is set to 1..8 by sub_E527 (which keeps dp[$B0]
 * cycling 0..7 and writes dp[$B0]+1 → dp[$88]); index 0 routes to $81A4
 * (a bare RTS, no transfer this frame). The shared DMA-trigger tail at
 * $821A loads $4300=$01 (CPU→PPU word, fixed src), $4301=$18 (B-bus =
 * $2118 = VMDATAL), $4304=$00 (src bank), $4305=$0800 (len), then
 * MDMAEN=$01. */
static void vram_stream_step_814F(void)
{
    /* Index 0 = no-op (RTS at $81A4). Indices 1..8 each map to a 5-step
     * setup block at $81A5/$81B4/$81C3/$81D2/$81E1/$81F0/$81FF/$820E. */
    static const struct { uint16_t src; uint16_t vram_dst; } stream[9] = {
        { 0x0000, 0x0000 },               /* index 0 → no-op */
        { 0x3000, 0x0800 },               /* $81A5 */
        { 0x3800, 0x0C00 },               /* $81B4 */
        { 0x4000, 0x1000 },               /* $81C3 */
        { 0x4800, 0x1400 },               /* $81D2 */
        { 0x5000, 0x1800 },               /* $81E1 */
        { 0x5800, 0x1C00 },               /* $81F0 */
        { 0x6000, 0x2000 },               /* $81FF */
        { 0x6800, 0x2400 },               /* $820E (falls through into
                                             $821A shared tail) */
    };
    unsigned i = dp[0x88];
    if (i == 0 || i > 8) return;                /* index 0 = $81A4 RTS */
    DMA0_SRC   = stream[i].src;
    VMADDL     = stream[i].vram_dst;
    /* Shared DMA-trigger tail @ $821A:
     *   DMA0_PARAM=$01 (CPU→PPU, fixed src, word), DMA0_DEST=$18,
     *   DMA0_BANK=$00, DMA0_LEN=$0800, MDMAEN=$01. */
}

/* sub_8553 / sub_85B2 — alternate frames. Both currently look like early
 * returns until a state condition is met. Lifting the bodies past their
 * guards is future work. */
static void per_frame_even_8553(void) { if (dp[0x57] == dp[0x58]) return; }
static void per_frame_odd_85B2(void)  { if (dp[0x5B] >= 4)         return; }

/* sub_C804 — VRAM update queue at $00:0C00.
 *   Batch format: [VMADDR][data...][$FFFF terminator].
 *   dp[$2C..$2D] = total bytes used; reset to 0 after flush. */
static void vram_queue_flush_C804(void)
{
    uint16_t end = *(uint16_t *)&dp[0x2C];
    if (end == 0) return;
    uint16_t *q = (uint16_t *)&wram[0x0C00];
    unsigned i = 0;
    while (i*2 < end) {
        VMADDL = q[i++];
        while (i*2 < end) {
            uint16_t w = q[i++];
            if (w == 0xFFFF) break;
            VMDATAL       = (uint8_t)w;
            MMIO8(0x2119) = w >> 8;
        }
    }
    *(uint16_t *)&dp[0x2C] = 0;
}

/* sub_8937 — CGRAM (palette) update-queue flusher. NOT an OAM index
 * reset (previous lift was wrong — verified at $00:8937 the body walks
 * the table at $0F20, NOT the OAM allocator).
 *
 * Format of the queue at WRAM $0F20:
 *   byte 0 = CGRAM index (written to CGADD $2121)
 *   byte 1 = low color byte (written to CGDATA $2122)
 *   byte 2 = high color byte (written to CGDATA $2122)
 * Total queue length (in bytes) is at dp[$2E..$2F] (16-bit). On exit
 * dp[$2E] is zeroed.
 *
 * Asm:
 *   LDX #$0000
 * loop:
 *   CPX $2E
 *   BNE $8944       ; if not done, process a triple
 *   LDY #$0000 / STY $2E / RTS
 * $8944:
 *   LDA $0F20,x / INX / STA $2121
 *   LDA $0F20,x / INX / STA $2122
 *   LDA $0F20,x / INX / STA $2122
 *   BRA loop
 */
static void cgram_queue_flush_8937(void)
{
    uint16_t queue_len = *(uint16_t *)&dp[0x2E];
    if (queue_len == 0) {
        *(uint16_t *)&dp[0x2E] = 0;             /* matches asm STY $2E */
        return;
    }
    for (uint16_t x = 0; x < queue_len; ) {
        MMIO8(0x2121) = wram[0x0F20 + x]; ++x;  /* CGADD */
        MMIO8(0x2122) = wram[0x0F20 + x]; ++x;  /* CGDATA low */
        MMIO8(0x2122) = wram[0x0F20 + x]; ++x;  /* CGDATA high */
    }
    *(uint16_t *)&dp[0x2E] = 0;
}
/* Old (wrong) name retained for callers; redirects to the real body. */
static void oam_index_reset_8937(void) { cgram_queue_flush_8937(); }

/* sub_884A — BG1/BG2/BG3 H+V scroll push (write-twice register protocol).
 * BG4 scroll is not touched (the game uses 3 BG layers). */
static void bg_scroll_push_884A(void)
{
    BG1HOFS = dp[0x46]; BG1HOFS = dp[0x47];
    BG1VOFS = dp[0x48]; BG1VOFS = dp[0x49];
    BG2HOFS = dp[0x4A]; BG2HOFS = dp[0x4B];
    BG2VOFS = dp[0x4C]; BG2VOFS = dp[0x4D];
    BG3HOFS = dp[0x4E]; BG3HOFS = dp[0x4F];
    BG3VOFS = dp[0x50]; BG3VOFS = dp[0x51];
}

/* sub_88A5 — park all 128 sprites off-screen in the shadow OAM at
 * $00:0D00, then reset the OAM allocators so the frame's draw code can
 * repopulate. */
static void shadow_oam_clear_88A5(void)
{
    uint16_t *oam = (uint16_t *)&wram[0x0D00];
    for (unsigned i = 0; i < 0x100; i += 2) oam[i] = 0xE080;
    for (unsigned i = 0x100; i < 0x110; ++i) oam[i] = 0x5555;
    *(uint16_t *)&dp[0x32] = 0x0010;
    *(uint16_t *)&dp[0x34] = 0x0110;
}

/* sub_049966 (JSL from NMI) — walk the entity table, dispatch handlers,
 * then trim trailing empty slots.
 *
 * Verified body:
 *   PHB / DBR = $04
 *   X = $0600                              ; start of table
 *   loop: CPX $30 / BCC body / fall_through
 *   body:
 *     LDA $0000,x (8-bit type)
 *     BEQ skip                              ; type 0 = empty
 *     XBA / LDA #0 / XBA / ASL              ; A = type*2 (no bounds clamp!)
 *     TAY
 *     REP #$20 / LDA $9A30,y / STA $82      ; 16-bit handler addr
 *     SEP #$20
 *     JSR $DCD2 (= JMP ($0082))             ; call handler with X = entity ptr
 *   skip:
 *     X += 20
 *     BRA loop
 *   JSR $999A                                ; trim trailing empty slots
 *   PLB / RTL
 *
 * The trim helper at $04:999A walks BACKWARD from end of table to the
 * sentinel $05EC, finds the last non-zero type, and updates dp[$30] to
 * one-past-it so future iterations stop earlier.
 *
 * Note: there is NO bounds clamp on the type byte — the spawner must
 * keep type < 118 (the table size is 118 entries; values $76+ would
 * fetch garbage handlers). */
static void entity_table_compact_04999A(void)
{
    /* Faithful port of $04:999A: walk backward from the slot BEFORE the
     * current end (i.e. starting at X = walker's final X, which is the
     * smallest X >= dp[$30]). Stop at the sentinel $05EC (= $0600 - 20)
     * OR at the first non-empty slot. dp[$30] becomes that X + 20.
     *
     * Walker exits with X = some value >= dp[$30]. The walker increments
     * X by 20 each iteration starting from $0600, so X is always
     * $0600 + 20*k for some k >= 0. */
    uint16_t x = ENTITY_END;
    if (x < 0x0600) x = 0x0600;                  /* walker's first X */
    for (;;) {
        x -= sizeof(Entity);                      /* SBC #$0014 */
        if (x == 0x05EC) break;                   /* sentinel */
        if (wram[x] != 0) break;                  /* live entity */
    }
    ENTITY_END = x + sizeof(Entity);
}

static void entity_step_all_049966(void)
{
    /* ENTITY_END is the ABSOLUTE end-pointer (NOT an offset). Initial
     * value at boot is $0001, which makes the loop exit immediately
     * (since X starts at $0600 > $0001). After spawn_entity ($04:99C1),
     * dp[$30..$31] becomes "(slot_addr + 20)" so the walker reaches
     * exactly that slot. */
    for (unsigned x = 0x0600; x < ENTITY_END; x += sizeof(Entity)) {
        Entity *e = (Entity *)&wram[x];
        if (e->type == 0) continue;
        entity_handlers[e->type](e);
    }
    entity_table_compact_04999A();
}

/* sub_8101 — START button -> pause. Gated by dp[$71] (the "menu open"
 * lockout). Reads dp[$0161], which is the JOY1H shadow. */
static void pause_toggle_on_start_8101(void)
{
    if (dp[0x0071]) return;
    if (dp[0x0161] & 0x10) dp[0x002A] = 1;     /* bit 4 of JOY1H = START */
}

/* ========================================================================
 * CURSOR ENTITY (type 01) — $04:9D9D
 *
 * Polled every NMI via the entity walker. The cursor "entity" is really
 * just an input pickup that decides whether the player pressed A or a
 * B/Y combination — then dispatches to the shared action handler at
 * $9DB9. dp[$60..$61] are the "freshly pressed" joypad edge bits (not
 * the raw $0160/$0161, which are current-frame).
 *
 * Verified disassembly @ $04:9D9D:
 *   LDA $0071
 *   BNE $9DB1        ; menu-open path — DOES NOT EARLY-RETURN; jumps to
 *                    ;   the mouse-edge fallback at $9DB1 which still
 *                    ;   accepts left/right clicks
 *   LDA $60 / AND #$80 / BNE $9DB9     ; A button just pressed
 *   LDA $61 / AND #$90 / BNE $9DB9     ; B or Y just pressed
 *   RTS
 *
 * $9DB1 (menu-locked fallback):
 *   LDA $007D / AND #$03 / BNE $9DB9   ; mouse left/right button edges
 *   RTS
 *
 * Both paths converge on $9DB9 (the action handler).
 * ======================================================================== */
static void cursor_action_A_9DB9(void);    /* shared action target */
static void cursor_action_B_9DB1(void);    /* menu-locked mouse fallback */

static void cursor_handler_04_9D9D(Entity *self)
{
    (void)self;
    if (dp[0x0071]) {                    /* menu open -> mouse fallback   */
        cursor_action_B_9DB1();
        return;
    }
    if (dp[0x60] & 0x80) {                /* bit 7 of $60 = A button edge  */
        cursor_action_A_9DB9();
        return;
    }
    if (dp[0x61] & 0x90) {                /* bits 7+4: B or Y edges        */
        cursor_action_A_9DB9();
        return;
    }
    /* nothing pressed this frame */
}
/* $04:9DB1 — menu-locked fallback. Accepts mouse buttons via dp[$007D]
 * (the just-pressed edge mask from the mouse BIOS). Bits 0+1 of $007D
 * mirror the mouse's left+right buttons after the BIOS re-packs them. */
static void cursor_action_A_9DB9(void) { /* TODO: $04:9DB9 action body */ }
static void cursor_action_B_9DB1(void)
{
    if (dp[0x007D] & 0x03) cursor_action_A_9DB9();
}

/* ========================================================================
 * VIEW SWITCH on SELECT press — $00:A3BD
 *
 * Sets dp[$0B] (the game state) to one of:
 *   $1B               if dp[$02B3] == 0  ("view changed" flag clear)
 *   $1D + 2*dp[$02B1] otherwise          (per-view return state)
 *
 * dp[$02B1] is the current view (one of the 6 ViewMode values), so the
 * resulting state covers $1D, $1F, $21, $23, $25, $27.
 * ======================================================================== */
static void view_switch_state_A3BD(void)
{
    if (dp[0x02B3] == 0)
        dp[0x0B] = 0x1B;
    else
        dp[0x0B] = 0x1D + (dp[0x02B1] << 1);
}

/* sub_8611 — "play view-switch SFX (APU command $C4) + fade out". */
static void play_sfx_and_fade_8611(void)
{
    APUIO0 = 0xC4;
    /* the fade loop (DEC dp[$6C] from $0F to $00 writing INIDISP) */
}

/* ========================================================================
 * VBLANK SYNC + SELECT (toggle view) — $00:985F
 *
 * Standard "force vblank, run logic, re-enable NMI, sync inputs" pattern.
 * On SELECT release-edge, clears view mode (dp[$26]) and sets a "view
 * changed" flag (dp[$02B3]), then re-renders.
 * ======================================================================== */
static void sub_E527(void);
static void sub_DEEE(void);
/* sub_DF79 returns NONZERO if "settled" (the asm clears carry); ZERO if
 * the caller should re-loop via the retry helper (asm sets carry). The
 * vsync loop breaks out on "settled". */
static int  sub_DF79(void);
static void sub_A3D6(void);
static void sub_A354(void);
static void switch_view_A3BD(void);
static void after_view_change_8611(void);

/* External forward decl — defined in misc_helpers.c. */
extern void coop_yield_877D(void);

/* sub_985F — vblank-sync loop. Actual ROM entry is at $00:9859:
 *   JSR $877D / STZ $02E3 / [fall into $985F body]
 * Loop body at $985F:
 *   STZ NMITIMEN / JSR $E527 / NMITIMEN = $0A
 *   JSR $DEEE / JSR $DF79
 *   BCC $9877 (=break to A-button)  ; sub_DF79 returned carry-clear
 *   JSR $A3D6 / BRA $9859             ; retry path
 * After break:
 *   JSR $A354 (A button)
 *   if pause-locked: return
 *   else if SELECT held: STZ $26 / dp[$02B3]=1 / sub_A3BD / sub_8611 */
static void vsync_and_input_985F(void)
{
    coop_yield_877D();                /* $9859: JSR $877D before loop  */
    dp[0x02E3] = 0;
    for (;;) {
        NMITIMEN = 0;                 /* freeze NMI               */
        sub_E527();                   /* VRAM stream + tile-row queue  */
        NMITIMEN = dp[0x0A];          /* re-enable ($81)          */
        sub_DEEE();
        if (sub_DF79()) break;        /* "settled" => exit loop   */
        sub_A3D6();                   /* retry path               */
        coop_yield_877D();            /* asm BRA $9859 loops the yield */
        dp[0x02E3] = 0;
    }
    sub_A354();
    if (dp[0x0071]) return;           /* pause-locked => skip SELECT  */

    /* Note: reads $4219 (JOY1H) DIRECTLY, not the dp[$0161] shadow. */
    if (JOY1H & 0x20) {               /* SELECT held (bit 5)      */
        dp[0x0026]  = 0;
        dp[0x02B3]  = 1;               /* "view changed" flag      */
        switch_view_A3BD();
        after_view_change_8611();
    }
}

/* ========================================================================
 * SRAM SAVE GAME — 32 KB at $70:0000-$70:7FFF
 *
 * Layout discovered so far:
 *   $70:0000           save data (bulk; first byte is a header)
 *   $70:0005           early field (game type? scenario level?)
 *   $70:547F           checksum byte (read at $03:F9A3 / $03:F9D4)
 *   $70:7FA0/A1/A2     3-byte signature written by save_signature_AA2E
 *                      (the "save valid" probe — A1/A2 = clock minutes/hours)
 *
 * Save serializer call chain:
 *   $00:959D save_game_959D     -> JSL $02:801F -> JSL $03:FA74 (real serializer)
 * Asset/decompress chain:
 *   $00:8D7E asset_load_to_vram -> JSL $02:8010 -> JSL $03:8467 (decompressor)
 * ======================================================================== */

/* sub_AA2E — write the 3-byte SRAM signature. Caller passes A (the magic
 * byte); the routine also samples clock state from dp[$03..$04]. */
static void save_signature_write_AA2E(uint8_t magic)
{
    sram[0x7FA0] = magic;
    sram[0x7FA1] = dp[0x04];          /* clock: hours   */
    sram[0x7FA2] = dp[0x03];          /* clock: minutes */
}

/* sub_959D — entry into the full-save flow. The caller passes the first
 * byte in A; we mirror to $70:0000, ack NMI, set up parameters, call the
 * deep serializer at $03:FA74, set "save complete" at dp[$0055], and
 * transition to GS_AFTER_SAVE ($1A). */
static void save_game_959D(uint8_t first_byte);

/* ========================================================================
 * LZSS DECOMPRESSOR — $03:8467 (called via $02:8010 from $00:8D7E)
 *
 * See wiki/16-rendering-pipeline.md §8 for the LZSS format specification
 * verified across all 43 LZSS-compressed art assets. (The same codec is
 * re-used by the save system for the DOBBY/DURRY body — see
 * wiki/18-save-load.md §2.)
 *
 * Format decoded from the disassembly:
 *
 *   Header: 4 bytes
 *     [0..1]  uncompressed length (little-endian)
 *     [2..3]  skipped (probably reserved / unused)
 *
 *   Body: groups of 9 bytes max
 *     Each group starts with one "control byte". Bits are consumed MSB-first
 *     (the original uses ASL on a 16-bit register pre-seeded with $FF00 so
 *     the low byte counts off 8 shifts then the high $FF underflows).
 *       bit=0 -> emit one literal byte  (1 byte from stream)
 *       bit=1 -> back-reference          (2 bytes from stream):
 *                  bytes[0..1] together form a 16-bit field B
 *                    offset_back = (B >> 4) & 0x0FFF
 *                    length      = (B & 0x0F) + 3
 *                  Copy `length` bytes from out_pos-1-offset_back to out_pos.
 *
 *   Source pointer:  dp[$CF..$D1]      (24-bit; high byte = bank in dp[$D1])
 *   Output pointer:  dp[$D4..$D6]      (24-bit; dest set up by $00:8D7E to
 *                                       $7E:2000)
 *
 * Routine internals:
 *   sub_$03:8456     "read one byte from source and advance pointer"
 *   The decompressor uses DP=$0200 internally (TCD #$0200) so $C7-$DF refer
 *   to wram[$02C7..$02DF].
 * ======================================================================== */

/* Source byte reader. The original increments dp[$C7..$C9] and handles the
 * 16-bit bank rollover via ROR/INC at lines $843x. */
static uint8_t lz_read_byte(uint32_t *src24)
{
    uint8_t b = (*src24 < 0x100000) ? wram[*src24] : 0;
    (*src24)++;
    return b;
}

static void lz_decompress_03_8467(uint32_t src24, uint32_t dst24)
{
    uint16_t out_len = lz_read_byte(&src24);
    out_len |= lz_read_byte(&src24) << 8;
    (void)lz_read_byte(&src24);              /* skip 2 reserved bytes */
    (void)lz_read_byte(&src24);

    uint8_t *out = &wram[dst24 & 0x1FFFF];
    uint16_t out_pos = 0;
    while (out_pos < out_len) {
        uint8_t ctrl = lz_read_byte(&src24);
        for (unsigned bit = 0; bit < 8 && out_pos < out_len; ++bit) {
            if ((ctrl & 0x80) == 0) {
                /* literal */
                out[out_pos++] = lz_read_byte(&src24);
            } else {
                /* back-reference: 2 bytes, packed 12+4 */
                uint16_t b = lz_read_byte(&src24);
                b |= lz_read_byte(&src24) << 8;
                uint16_t offset = (b >> 4) & 0x0FFF;
                uint16_t length = (b & 0x0F) + 3;
                uint16_t src_pos = out_pos - 1 - offset;
                for (uint16_t i = 0; i < length && out_pos < out_len; ++i)
                    out[out_pos++] = out[src_pos++];
            }
            ctrl <<= 1;
        }
    }
}

/* ========================================================================
 * VRAM ASSET LOADER ($00:8D7E) and DMA-into-VRAM ($00:8ACC)
 *
 * Pattern: every state handler calls the loader two or three times:
 *   LDA #<count> / LDY #<ROM ptr> / JSR $8D7E   ; decompress to $7E:2000
 *   LDX #<bytes> / LDY #<VRAM dst> / JSR $8ACC  ; DMA to VRAM
 * ======================================================================== */
static void asset_decompress_to_scratch_8D7E(uint8_t count, uint16_t src)
{
    dp[0x02D1] = count;
    *(uint16_t *)&dp[0x02CF] = src;
    *(uint16_t *)&dp[0x02D4] = 0x2000;        /* dest low = $2000      */
    dp[0x02D6] = 0x7E;                         /* dest bank = $7E       */
    /* JSL $02:8010 -> JSL $03:8467 (the actual LZ-style decompressor). */
}

static void vram_dma_from_scratch_8ACC(uint16_t length, uint16_t vram_dst)
{
    DMA0_LEN   = length;
    VMADDL     = vram_dst;
    DMA0_PARAM = 0x01;        /* 2-register write to fixed dest */
    DMA0_DEST  = 0x18;        /* $2118 (VMDATAL/H)              */
    DMA0_SRC   = 0x2000;
    DMA0_BANK  = 0x7E;
    MDMAEN     = 0x01;
}

/* ========================================================================
 * SPC700 SOUND DRIVER UPLOAD ($08:8006)
 *
 * Classic Nintendo IPL handshake: read 4-byte chunks from a 24-bit source
 * pointer in dp[$E7..$E9], pack into A/X/Y, send via JSR $817A. At end of
 * stream, write 0 to APUIO0+APUIO2 (long), then poll APUIO0 with BPL until
 * the SPC ack flips bit 7. Returns via JSL/RTL.
 *
 * Called once at boot from sub_BB8D with X=$0A00. The data at $08:0A00
 * onward is the SPC700 driver + initial soundbank.
 * ======================================================================== */
static void spc700_iram_byte_send_817A(uint8_t b);
static void spc700_upload_driver_088006(uint16_t src_offset_in_bank8);

/* ========================================================================
 * BOOT INIT — sub_BB8D ($00:BB8D)
 * ======================================================================== */
static void sub_BC7F(void);           /* PPU bring-up    */
static void sub_C318(void);
static void sub_8D94(void);
static void sub_E494(uint16_t x);
static void sub_BC53(void);

/* Persistent shadow at $7F:E710 onward — sub_BB8D seeds 5 16-bit values
 * here. Suspected purpose: SRAM-mirror used by the save/load path. */
static void seed_persistent_shadow(void)
{
    static const uint16_t init[5] = { 0x0013, 0x0044, 0x0009, 0x001C, 0x0182 };
    for (unsigned i = 0; i < 5; ++i)
        *(uint16_t *)&wram[0x1E710 + 2*i] = init[i];
    wram[0x1E745] = 0;
}

static void boot_init_BB8D(void)
{
    INIDISP = 0x80;                    /* force blank                       */
    sub_BC7F();                        /* PPU registers + tilemap defaults  */
    dp[0x0A] = 0x81;                   /* NMITIMEN value: NMI + joypad AR   */
    sub_C318();
    dp[0x0032] = 0xFF;
    dp[0x89]   = 0x78;
    sub_8D94();
    dp[0x0030] = 0x01;                 /* entity-table end = 1 byte         */
    dp[0x0031] = 0x00;
    dp[0x002F] = 0x28;
    dp[0x8C]   = 0x2C;
    dp[0x002E] = 0x2C;
    dp[0x64]   = 0x04;
    dp[0x02B1] = dp[0x02B3] = dp[0x02B4] = 0;
    dp[0x44]   = dp[0x45]   = 0;
    dp[0x0081] = 0;
    dp[0x21]   = 0;
    dp[0x004E] = 0xFF;
    dp[0x0033] = dp[0x0034] = dp[0x0035] = dp[0x0036] = 0x01;
    dp[0x0037] = dp[0x0038] = dp[0x0039] = dp[0x003A] = 0;
    dp[0x0045] = 0x01;
    dp[0x0046] = 0x00;
    dp[0x0047] = dp[0x0048] = 0xFF;
    dp[0x0044] = dp[0x004F] = 0x01;
    dp[0x0269] = 0;

    seed_persistent_shadow();
    spc700_upload_driver_088006(/*src=*/0x0A00);

    dp[0x0073] = 0x02;
    sub_E494(/*x=*/0x0000);
    sub_BC53();
}

/* sub_896D — enable NMI by writing the saved $81 to NMITIMEN. */
static void sub_8967(void);
static void enable_nmi_896D(void)
{
    sub_8967();
    NMITIMEN = dp[0x0A];                /* $81 = NMI on, joypad AR on */
}

/* ========================================================================
 * Game-state handlers (the 10 entries from the $9369 table). Lifted from
 * the prologues in dig.txt; each one configures a screen then advances.
 * ======================================================================== */

/* Common helpers used by the handlers. */
static void apu_silence_all(void)
{
    APUIO0 = 0; APUIO1 = 0; APUIO2 = 0; APUIO3 = 0;
}
static void sub_8841(uint8_t a);    /* "wait A frames" or similar      */
static void sub_BB38(void);         /* per-screen common setup         */
static void sub_BA9E(uint8_t a);    /* screen template by index        */
static void sub_BACA(uint8_t a, uint16_t y);  /* (a=count, y=ptr?)     */
static void sub_BAF2(void);
static void sub_85FC(void);
static void sub_8616_fade_out(void);
/* sub_877D forward decl removed — was an empty static stub that shadowed the
 * real cooperative-yield body in misc_helpers.c (and lifted_helpers_6.c).
 * Call sites in this TU now invoke the extern coop_yield_877D directly. */
static void sub_8611(void);
static int  state_scenario_check_loaded(void) { return TASK_LIMIT == 4; }

static void gs_full_game(void)
{
    apu_silence_all();
    sub_8841(0x04);
    enable_nmi_896D();
    INIDISP = 0x80;
    sub_BB38();
    asset_decompress_to_scratch_8D7E(0x16, 0x9D63);
    vram_dma_from_scratch_8ACC(0x2000, 0x0000);
    asset_decompress_to_scratch_8D7E(0x1E, 0xFA24);
    vram_dma_from_scratch_8ACC(0x0800, 0x7000);
    /* ... more setup, then ultimately INC dp[$0B] */
    dp[0x0B]++;
}

static void gs_scenario_game(void)
{
    while (TASK_LIMIT != 0x04) coop_yield_877D();  /* F6: was empty static stub sub_877D() */
    sub_8616_fade_out();
    dp[0x0B]++;
}

static void gs_tutorial(void)
{
    sub_BA9E(0x04);
    sub_8616_fade_out();
    dp[0x0B]++;
}

static void gs_marriage_flight(void)        /* "MARRIGE" [sic] string */
{
    sub_BA9E(0x03);
    sub_BACA(0x05, 0x903C);
    sub_8616_fade_out();
    dp[0x0B]++;
}

static void gs_game_over(void)
{
    enable_nmi_896D();
    INIDISP = 0x80;
    /* sub_B1D2 (not lifted), then a JSL $0499C1 with X=$88, Y=$98, A=$5E
     * — this spawns entity type $5E at screen pos (136, 152). */
    enable_nmi_896D();
    sub_85FC();
    dp[0x0B]++;
}

static void gs_sound(void)
{
    sub_BA9E(0x03);
    sub_BACA(0x05, 0x908D);
    sub_8616_fade_out();
    dp[0x0B]++;
}

/* (gs_saved_game, gs_ant_information, gs_full_end, gs_scenario_end follow
 * the same template — call apu_silence_all + enable_nmi_896D + a series of
 * asset_decompress / vram_dma pairs, then INC dp[$0B]. Bodies omitted to
 * keep this file readable; see dig.txt lines 415-540.) */

/* ========================================================================
 * Unresolved stubs (named so we can grep for them in disasm.txt)
 * ======================================================================== */
static void sub_8967(void)            { /* TODO */ }
static void sub_BC7F(void)            { /* TODO: PPU/VRAM defaults     */ }
static void sub_C318(void)            { /* TODO */ }
static void sub_8D94(void)            { /* TODO */ }
static void sub_E494(uint16_t x)      { (void)x; /* TODO */ }
static void sub_BC53(void)            { /* TODO */ }
static void sub_E527(void)            { /* TODO */ }
static void sub_DEEE(void)            { /* TODO */ }
static int  sub_DF79(void)
{
    /* Faithful: $00:DF79 calls $E201, then compares dp[$02BD] (16-bit)
     * to dp[$02BB] (16-bit). If equal, CLC and RTS (settled). Otherwise
     * falls into the $DF86 body which updates dp[$02BD]/$0026 etc. and
     * returns with SEC (caller re-loops). For the C model we return
     * NONZERO on "settled" so the caller's `if (sub_DF79()) break;` is
     * natural. */
    extern void sub_E201(void);
    sub_E201();
    return (*(uint16_t *)&dp[0x02BD]) == (*(uint16_t *)&dp[0x02BB]);
}
static void sub_A3D6(void)            { /* TODO */ }
static void sub_A354(void)            { /* TODO */ }
static void switch_view_A3BD(void)    { /* TODO */ }
static void after_view_change_8611(void){ /* TODO */ }
static void sub_8841(uint8_t a)       { (void)a; /* wait? */ }
static void sub_BB38(void)            { /* TODO */ }
static void sub_BA9E(uint8_t a)       { (void)a; /* screen template */ }
static void sub_BACA(uint8_t a, uint16_t y) { (void)a; (void)y; /* TODO */ }
static void sub_BAF2(void)            { /* TODO */ }
static void sub_85FC(void)            { /* TODO */ }
static void sub_8616_fade_out(void)   { /* see $00:8616 */ }
/* F6: empty static sub_877D() removed — see coop_yield_877D (misc_helpers.c). */
static void sub_8611(void)            { /* TODO */ }
static void spc700_iram_byte_send_817A(uint8_t b) { (void)b; }
static void spc700_upload_driver_088006(uint16_t src) { (void)src; }
static void save_game_959D(uint8_t b) { (void)b; }

/* Per-type init tables (ROM, bank $01). Decoded values for reference. */
const uint16_t entity_init_word[32] = {
    [9]=0x014C, [10]=0x0100, [11]=0x0180, [12]=0x0140, [13]=0x0180,
    [17]=0x01C0, [18]=0x0100, [19]=0x0100, [22]=0x0100,
    [25]=0x0008, [30]=0x0080,
};
const uint8_t  entity_init_attr[32] = {
    0,0, 0x18, 0,0,0,0,0,0,
    0x1E, 0x9E, 0x9E, 0x9F, 0x9E,
    0x1F, 0x9E, 0x9F, 0x9F, 0x9E, 0x9E,
    0, 0x9F, 0x9E, 0x9F, 0x98, 0x98,
    0, 0x9E, 0x9F, 0, 0x9C, 0,
};

EntityHandler entity_handlers[32];  /* populated at boot from ROM */

/* ========================================================================
 * Vector table (informational)
 * ======================================================================== */
struct snes_vectors {
    void (*cop)(void);    void (*brk)(void);   void (*abrt)(void);
    void (*nmi)(void);    void (*irq)(void);   void (*reset)(void);
};
__attribute__((used))
static const struct snes_vectors native_vectors = {
    .nmi   = nmi,        /* $803E */
    .reset = reset,      /* $8009 */
};

/* All file-scope routines below are intentionally retained as
 * documentation for ROM addresses, even when nothing calls them in this
 * skeleton. Mark them used so -Wunused-function stays quiet. */
__attribute__((used)) static void const * const _doc_refs[] = {
    (void const *)main_9340,
    (void const *)game_state_dispatch_935C,
    (void const *)vsync_and_input_985F,
    (void const *)gs_full_game,    (void const *)gs_scenario_game,
    (void const *)gs_tutorial,     (void const *)gs_marriage_flight,
    (void const *)gs_game_over,    (void const *)gs_sound,
    (void const *)save_signature_write_AA2E,
    (void const *)save_game_959D,
    (void const *)spc700_iram_byte_send_817A,
    (void const *)spc700_upload_driver_088006,
    (void const *)sub_BAF2,        (void const *)sub_8611,
    (void const *)state_scenario_check_loaded,
    (void const *)cursor_handler_04_9D9D,
    (void const *)cursor_action_A_9DB9,
    (void const *)cursor_action_B_9DB1,
    (void const *)view_switch_state_A3BD,
    (void const *)play_sfx_and_fade_8611,
    (void const *)lz_decompress_03_8467,
};
