/*
 * text_content.c — extracted English text content of SimAnt (SNES).
 *
 * Auto-generated by extract_text.py from simant.sfc.  See
 * text_screens.c for the pointer-table layout (encyclopedia + tutorial)
 * and player_actions.c / scenarios.c for the short prompts.
 *
 * Text grammar (per Agent M):
 *   $FF      end-of-message
 *   $FE      newline (rendered as '\n' here)
 *   $2C/$2E  comma / period (suppress wrap at column edge)
 *   ASCII    otherwise
 *
 * Each encyclopedia page carries metadata so the renderer can
 * pair the prose with its 256-color palette + compressed picture:
 *   .palette_idx  → ROM addr $07:9D80 + (idx << 7) (128-byte CGRAM)
 *   .picture_src_bank / .picture_src_offset
 *                 → asset_decompress_028010() source
 *
 * Totals: encyclopedia = 8963 raw bytes across 30 pages,
 *         tutorial     = 5369 raw bytes across 54 messages.
 */

#include <stdint.h>

/* ============================================================
 * ENCYCLOPEDIA — 30 pages, 5 topics
 *   Topic 0  Introduction      pages  0..5    (6 pages)
 *   Topic 1  Ant Life          pages  6..16   (11 pages)
 *   Topic 2  Ants at Home      pages 17..19   (3 pages)
 *   Topic 3  Ants & Relatives  pages 20..25   (6 pages)
 *   Topic 4  SimAnt Strategy   pages 26..29   (4 pages)
 * ============================================================ */

typedef struct {
    uint8_t  page_index;          /* 0..29                              */
    uint8_t  palette_idx;         /* $01:C778[page]                     */
    uint8_t  picture_src_bank;    /* $01:C796[page]                     */
    uint16_t picture_src_offset;  /* $01:C7B4[page]                     */
    uint16_t text_rom_ptr;        /* $01:C7F0[page] (in bank $01)       */
    const char *topic;            /* topic name, for debug              */
    const char *text;             /* decoded English text               */
} EncyclopediaPage;

static const EncyclopediaPage encyclopedia_pages_full[30] = {
    /* page  0 — Introduction */
    {
        .page_index         = 0,
        .palette_idx        = 0x00,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0x8000,
        .text_rom_ptr       = 0xC82C,
        .topic              = "Introduction",
        .text =
            "SimAnt is based on\n"
            "real ants.\n"
            "Knowing about real ants\n"
            "will improve your game\n"
            "play.\n"
            "Ants live in social groups\n"
            "called colonies. They can't\n"
            "live without their colony,\n"
            "and will give up their\n"
            "lives to protect it. Each\n"
            "colony has a Queen. If the\n"
            "queen dies, the colony dies."
        ,
    },
    /* page  1 — Introduction */
    {
        .page_index         = 1,
        .palette_idx        = 0x00,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0x88E4,
        .text_rom_ptr       = 0xC93A,
        .topic              = "Introduction",
        .text =
            "Ants are insects. They\n"
            "are the most numerous\n"
            "insects in the world.\n"
            "Like all insects, they have\n"
            "six legs, and their\n"
            "bodies are divided into\n"
            "three parts: head,\n"
            "thorax, and abdomen."
        ,
    },
    /* page  2 — Introduction */
    {
        .page_index         = 2,
        .palette_idx        = 0x00,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0x9238,
        .text_rom_ptr       = 0xC9ED,
        .topic              = "Introduction",
        .text =
            "The ant's head has a\n"
            "mouth, two antennae, two\n"
            "kinds of eyes, and a\n"
            "brain. Ants' brains are\n"
            "very small, but they're\n"
            "smart for insects. They\n"
            "can remember pathways to\n"
            "food even after months of\n"
            "hibernation."
        ,
    },
    /* page  3 — Introduction */
    {
        .page_index         = 3,
        .palette_idx        = 0x00,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0x9D39,
        .text_rom_ptr       = 0xCAB8,
        .topic              = "Introduction",
        .text =
            "Ants have two big eyes\n"
            "that are made of many tiny\n"
            "segments. These eyes are\n"
            "good for seeing movement.\n"
            "Most ants also have smaller\n"
            "eyes that see light and\n"
            "dark. Ants use their jaws\n"
            "(called mandibles) to\n"
            "dig holes, carry things\n"
            "and fight. Ants smell with\n"
            "their feelers."
        ,
    },
    /* page  4 — Introduction */
    {
        .page_index         = 4,
        .palette_idx        = 0x00,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xA76E,
        .text_rom_ptr       = 0xCBC3,
        .topic              = "Introduction",
        .text =
            "The middle part of the ant\n"
            "is the thorax. All six legs\n"
            "connect to the thorax. The\n"
            "end of each leg has a foot\n"
            "with two hooked claws that\n"
            "let ants walk up walls or\n"
            "even across ceilings. Near\n"
            "the foot is a hook that the\n"
            "ant uses to comb and clean\n"
            "itself."
        ,
    },
    /* page  5 — Introduction */
    {
        .page_index         = 5,
        .palette_idx        = 0x02,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xB113,
        .text_rom_ptr       = 0xCCBF,
        .topic              = "Introduction",
        .text =
            "The rear of the ant, the\n"
            "abdomen, is where food is\n"
            "digested. Ants have two\n"
            "stomachs: one for their own\n"
            "food and one to hold food\n"
            "to share with other ants."
        ,
    },
    /* page  6 — Ant Life */
    {
        .page_index         = 6,
        .palette_idx        = 0x06,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xBCD9,
        .text_rom_ptr       = 0xCD5A,
        .topic              = "Ant Life",
        .text =
            "There are different types,\n"
            "or Castes, of ants. Each\n"
            "caste has a purpose in the\n"
            "colony. The main castes are\n"
            "Queen, Worker, Soldier, and\n"
            "Male. There's usually only\n"
            "one queen per colony. She's\n"
            "the only ant that lays eggs,\n"
            "and is the mother of all\n"
            "the other ants in the\n"
            "colony.\n"
            "Most queens have wings when\n"
            "they are young, but the\n"
            "wings fall off after the \n"
            "mating flight. Queens are\n"
            "the largest ants, and can\n"
            "live as long as 20 years."
        ,
    },
    /* page  7 — Ant Life */
    {
        .page_index         = 7,
        .palette_idx        = 0x00,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xC53A,
        .text_rom_ptr       = 0xCF08,
        .topic              = "Ant Life",
        .text =
            "Workers are the smallest \n"
            "and most numerous ants in\n"
            "the colony. They are female,\n"
            "but cannot lay eggs.\n"
            "Workers search for food\n"
            "(forage), take care of\n"
            "the young (nurse), dig\n"
            "tunnels, guard the queen\n"
            "and defend the nest from\n"
            "enemies. They only live\n"
            "from one to four years."
        ,
    },
    /* page  8 — Ant Life */
    {
        .page_index         = 8,
        .palette_idx        = 0x00,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xCB6E,
        .text_rom_ptr       = 0xD016,
        .topic              = "Ant Life",
        .text =
            "Soldier ants are all\n"
            "females that cannot lay\n"
            "eggs. Soldiers do all\n"
            "the jobs that workers\n"
            "do, but they are larger,\n"
            "with big heads and strong\n"
            "jaws so they are better\n"
            "fighters."
        ,
    },
    /* page  9 — Ant Life */
    {
        .page_index         = 9,
        .palette_idx        = 0x06,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xD29A,
        .text_rom_ptr       = 0xD0C4,
        .topic              = "Ant Life",
        .text =
            "Male ants have wings.\n"
            "They don't do work. Their\n"
            "only purpose is to\n"
            "fertilize the queens.\n"
            "They die right after their\n"
            "mating flight."
        ,
    },
    /* page 10 — Ant Life */
    {
        .page_index         = 10,
        .palette_idx        = 0x00,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xDA5C,
        .text_rom_ptr       = 0xD147,
        .topic              = "Ant Life",
        .text =
            "Ants mostly communicate\n"
            "by smelling with their\n"
            "antennae. They can tell\n"
            "if another ant is a\n"
            "friend or enemy by its\n"
            "smell. They can tell\n"
            "their own nest by the\n"
            "smell. If ants are\n"
            "alarmed they release\n"
            "a smell that warns all\n"
            "the other ants. The \n"
            "chemicals that ants\n"
            "communicate with are\n"
            "called Pheromones."
        ,
    },
    /* page 11 — Ant Life */
    {
        .page_index         = 11,
        .palette_idx        = 0x00,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xE35D,
        .text_rom_ptr       = 0xD274,
        .topic              = "Ant Life",
        .text =
            "When ants find food,\n"
            "they need to let others\n"
            "know where it is. So, on\n"
            "the way home with food,\n"
            "ants drag their abdomens\n"
            "on the ground and leave\n"
            "a chemical trail that\n"
            "other ants can follow to\n"
            "the food."
        ,
    },
    /* page 12 — Ant Life */
    {
        .page_index         = 12,
        .palette_idx        = 0x00,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xEA5C,
        .text_rom_ptr       = 0xD33C,
        .topic              = "Ant Life",
        .text =
            "Ants are ruthless\n"
            "fighters that have\n"
            "no fear and no mercy.\n"
            "They fight with ants\n"
            "from other nests even if\n"
            "they are the same species.\n"
            "The main reasons they fight\n"
            "are for territory and food.\n"
            "Ants use their mandibles\n"
            "(jaws) to bite and pinch\n"
            "and stab. Most ants also\n"
            "produce poisons that they\n"
            "can spray their enemies\n"
            "with. Some ants have\n"
            "stingers."
        ,
    },
    /* page 13 — Ant Life */
    {
        .page_index         = 13,
        .palette_idx        = 0x08,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xF433,
        .text_rom_ptr       = 0xD494,
        .topic              = "Ant Life",
        .text =
            "Some ants act like\n"
            "ranchers and keep 'herds'\n"
            "of small insects called \n"
            "aphids. Aphids are small \n"
            "insects that sit on plants\n"
            "and suck so much sap\n"
            "that some squirts out\n"
            "behind them. Ants eat the\n"
            "sap, and in return, protect\n"
            "the aphids from ladybugs."
        ,
    },
    /* page 14 — Ant Life */
    {
        .page_index         = 14,
        .palette_idx        = 0x06,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xFE01,
        .text_rom_ptr       = 0xD58A,
        .topic              = "Ant Life",
        .text =
            "One ant job is nursing:\n"
            "taking care of the brood\n"
            "(eggs, larvae and pupae).\n"
            "Nurse ants clean and pro-\n"
            "tect the brood, keep\n"
            "them warm and dry, and \n"
            "carry them to safety if\n"
            "the nest is attacked."
        ,
    },
    /* page 15 — Ant Life */
    {
        .page_index         = 15,
        .palette_idx        = 0x00,
        .picture_src_bank   = 0x06,
        .picture_src_offset = 0x858E,
        .text_rom_ptr       = 0xD64A,
        .topic              = "Ant Life",
        .text =
            "Ants share food with each\n"
            "other, even after they've\n"
            "eaten it! Ants have an\n"
            "extra stomach called the\n"
            "CROP where they store food\n"
            "to share. If an ant is\n"
            "hungry, it goes up to\n"
            "another ant. If the second\n"
            "ant has food to share, it\n"
            "will spit it up into the\n"
            "hungry ant's face. Don't do\n"
            "this at home. These ants\n"
            "are professional insects."
        ,
    },
    /* page 16 — Ant Life */
    {
        .page_index         = 16,
        .palette_idx        = 0x0A,
        .picture_src_bank   = 0x06,
        .picture_src_offset = 0x8F96,
        .text_rom_ptr       = 0xD793,
        .topic              = "Ant Life",
        .text =
            "Some ants gather seeds and\n"
            "store them for the winter."
        ,
    },
    /* page 17 — Ants at Home */
    {
        .page_index         = 17,
        .palette_idx        = 0x07,
        .picture_src_bank   = 0x06,
        .picture_src_offset = 0x97CF,
        .text_rom_ptr       = 0xD7C9,
        .topic              = "Ants at Home",
        .text =
            "Ants build their nests in\n"
            "many places: under ground,\n"
            "under rocks, in mounds\n"
            "above ground, in rotten\n"
            "logs, inside trees and\n"
            "plants, and even inside\n"
            "the walls of human houses.\n"
            "Nests have many chambers,\n"
            "each with its own use. One\n"
            "chamber is for the queen.\n"
            "Other chambers are used for,\n"
            "nurseries, food storage\n"
            "and garbage dumps."
        ,
    },
    /* page 18 — Ants at Home */
    {
        .page_index         = 18,
        .palette_idx        = 0x0D,
        .picture_src_bank   = 0x06,
        .picture_src_offset = 0xA417,
        .text_rom_ptr       = 0xD90E,
        .topic              = "Ants at Home",
        .text =
            "Ants have four life stages:\n"
            "egg, larva, pupa and adult.\n"
            "The queen lays from 10 to\n"
            "hundreds of eggs every day.\n"
            "Nurse workers take the eggs\n"
            "from the queen's chamber\n"
            "to nurseries where they are\n"
            "cleaned and protected.\n"
            "After about two weeks, the\n"
            "eggs hatch into larvae.\n"
            "Larvae do nothing but eat\n"
            "to store energy for their\n"
            "next stage. After a few \n"
            "weeks, the larva weaves a\n"
            "cocoon around itself and\n"
            "becomes a pupa. After a few\n"
            "more weeks an adult ant \n"
            "emerges full grown from the\n"
            "cocoon."
        ,
    },
    /* page 19 — Ants at Home */
    {
        .page_index         = 19,
        .palette_idx        = 0x0E,
        .picture_src_bank   = 0x06,
        .picture_src_offset = 0xAE85,
        .text_rom_ptr       = 0xDAF0,
        .topic              = "Ants at Home",
        .text =
            "Ant colonies also have\n"
            "stages. The first stage,\n"
            "Founding is when the new\n"
            "Queen digs a small nest and\n"
            "begins laying eggs.\n"
            "The next stage is Expansion.\n"
            "Workers and Soldiers\n"
            "enlarge the nest and the\n"
            "Queen lays more eggs.\n"
            "When there are\n"
            "enough ants, the Queen\n"
            "produces winged ants--\n"
            "Males and New Queens.\n"
            "Next is Reproduction: the\n"
            "winged ants fly away to\n"
            "mate. The New Queens\n"
            "found new nests, and the\n"
            "ants left behind in the \n"
            "old colony go back into the\n"
            "Expansion stage and start\n"
            "over again."
        ,
    },
    /* page 20 — Ants & Relatives */
    {
        .page_index         = 20,
        .palette_idx        = 0x04,
        .picture_src_bank   = 0x06,
        .picture_src_offset = 0xB3DD,
        .text_rom_ptr       = 0xDCD8,
        .topic              = "Ants & Relatives",
        .text =
            "Bees are related to ants.\n"
            "They have a similar\n"
            "social structure. Bee\n"
            "colonies live in nests\n"
            "called hives. Hives\n"
            "can contain as many as\n"
            "30,000 bees. Out of all\n"
            "these bees, there is only\n"
            "one Queen and only about\n"
            "100 males. The rest are\n"
            "workers. If more than one\n"
            "queen is born in a hive at\n"
            "one time, they fight to the\n"
            "death, and the survivor\n"
            "rules the colony."
        ,
    },
    /* page 21 — Ants & Relatives */
    {
        .page_index         = 21,
        .palette_idx        = 0x05,
        .picture_src_bank   = 0x06,
        .picture_src_offset = 0xBCD5,
        .text_rom_ptr       = 0xDE3C,
        .topic              = "Ants & Relatives",
        .text =
            "Wasps are closely related\n"
            "to ants. It is believed\n"
            "that ants evolved from\n"
            "wasps 60 million years ago.\n"
            "Wasps are aggressive and\n"
            "have strong poison that\n"
            "hurts when they sting."
        ,
    },
    /* page 22 — Ants & Relatives */
    {
        .page_index         = 22,
        .palette_idx        = 0x03,
        .picture_src_bank   = 0x06,
        .picture_src_offset = 0xC4D6,
        .text_rom_ptr       = 0xDEE9,
        .topic              = "Ants & Relatives",
        .text =
            "Termite colonies have a\n"
            "social structure like ant\n"
            "colonies. They eat wood\n"
            "fiber, and do not make \n"
            "good house guests.\n"
            "Termites and ants don't\n"
            "get along. Ants often\n"
            "attack termite colonies\n"
            "and carry off their eggs\n"
            "and larvae for food."
        ,
    },
    /* page 23 — Ants & Relatives */
    {
        .page_index         = 23,
        .palette_idx        = 0x09,
        .picture_src_bank   = 0x06,
        .picture_src_offset = 0xC9AC,
        .text_rom_ptr       = 0xDFD2,
        .topic              = "Ants & Relatives",
        .text =
            "Out of over 8000 species\n"
            "of ants, one of the\n"
            "strangest is the Weaver ant\n"
            "from Africa, India and\n"
            "Australia. They make nests\n"
            "in trees by sewing leaves\n"
            "together with the silk that\n"
            "larvae produce to weave\n"
            "their cocoons. Workers\n"
            "hold the larvae in their\n"
            "mandibles and touch their\n"
            "mouths to each leaf. In\n"
            "addition to this child\n"
            "labor, Weaver ants are very\n"
            "vicious. Hundreds of them\n"
            "attack and bite anything\n"
            "that even bumps their tree."
        ,
    },
    /* page 24 — Ants & Relatives */
    {
        .page_index         = 24,
        .palette_idx        = 0x0B,
        .picture_src_bank   = 0x06,
        .picture_src_offset = 0xD47B,
        .text_rom_ptr       = 0xE17F,
        .topic              = "Ants & Relatives",
        .text =
            "African Army ants don't\n"
            "build nests. They travel\n"
            "all day, eating everything\n"
            "in sight, then, at night,\n"
            "form a living nest out of\n"
            "their bodies, with the\n"
            "queen in the middle. They\n"
            "have big, sharp mandibles,\n"
            "attack in groups, and can\n"
            "kill and eat insects,\n"
            "spiders, lizards and even\n"
            "mammals that are many times\n"
            "their size."
        ,
    },
    /* page 25 — Ants & Relatives */
    {
        .page_index         = 25,
        .palette_idx        = 0x0C,
        .picture_src_bank   = 0x06,
        .picture_src_offset = 0xDB68,
        .text_rom_ptr       = 0xE2BD,
        .topic              = "Ants & Relatives",
        .text =
            "Leafcutter Ants from\n"
            "South America are the\n"
            "farmers of the ant world.\n"
            "They build huge underground\n"
            "nests and grow their food.\n"
            "Thousands of Leafcutters\n"
            "go out on raids and bring\n"
            "back all the leaves they\n"
            "can find. Back in the nest,\n"
            "they cut the leaves into\n"
            "little pieces and chew them\n"
            "up, but they don't eat them.\n"
            "The chewed-up leaves are\n"
            "used as fertilizer to\n"
            "grow a type of fungus.\n"
            "This fungus is the only\n"
            "food Leafcutters can eat.\n"
            "Human farmers don't like\n"
            "Leafcutters because they\n"
            "destroy crops."
        ,
    },
    /* page 26 — SimAnt Strategy */
    {
        .page_index         = 26,
        .palette_idx        = 0x00,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xC53A,
        .text_rom_ptr       = 0xE4AC,
        .topic              = "SimAnt Strategy",
        .text =
            "The way to win SimAnt\n"
            "is to carefully manage\n"
            "your ants and their food.\n"
            "The more food you gather,\n"
            "the less the red ants get,\n"
            "and the faster your colony\n"
            "grows. Move the Yellow Ant\n"
            "to food, recruit help, then\n"
            "release the ants. As soon\n"
            "as more food appears, move\n"
            "the Yellow Ant there and\n"
            "recruit more help.\n"
            "To get the most out of\n"
            "your ants, at first produce\n"
            "mostly workers. Produce\n"
            "soldiers once your colony\n"
            "is well established with a\n"
            "good food supply.\n"
            "Don't produce Breeders\n"
            "until you need them."
        ,
    },
    /* page 27 — SimAnt Strategy */
    {
        .page_index         = 27,
        .palette_idx        = 0x06,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xD29A,
        .text_rom_ptr       = 0xE699,
        .topic              = "SimAnt Strategy",
        .text =
            "To win the Full Game, you\n"
            "must take over the whole\n"
            "yard and house, so you need\n"
            "to make a number of differ-\n"
            "ent nests. To do this,\n"
            "you'll need Breeders \n"
            "(winged ants). Wait until\n"
            "you have about 80 workers\n"
            "and soldiers, then set the\n"
            "Caste Control Panel to all\n"
            "Breeders. As soon as there\n"
            "are 20 Breeders, they will\n"
            "go on their mating flight.\n"
            "After the flight, be sure\n"
            "to reset the Caste Control."
        ,
    },
    /* page 28 — SimAnt Strategy */
    {
        .page_index         = 28,
        .palette_idx        = 0x00,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xCB6E,
        .text_rom_ptr       = 0xE822,
        .topic              = "SimAnt Strategy",
        .text =
            "The goal of the Scenario\n"
            "Game is to vanquish the\n"
            "red ants in eight differ-\n"
            "ent situations. These\n"
            "scenarios are won by doing\n"
            "battle, so you want to\n"
            "start producing soldiers\n"
            "fairly soon.\n"
            "Unlike the Full Game, the\n"
            "Scenario game has no need\n"
            "for Breeders, so don't\n"
            "waste your energy on them."
        ,
    },
    /* page 29 — SimAnt Strategy */
    {
        .page_index         = 29,
        .palette_idx        = 0x00,
        .picture_src_bank   = 0x05,
        .picture_src_offset = 0xBCD9,
        .text_rom_ptr       = 0xE941,
        .topic              = "SimAnt Strategy",
        .text =
            "After you play SimAnt, go\n"
            "outside and find some real\n"
            "ants. It won't be hard:\n"
            "ants are everywhere. Watch\n"
            "them as they forage for\n"
            "food and take it back to\n"
            "their nest, walk in paths,\n"
            "follow scent trails, face\n"
            "each other, and share food.\n"
            "What can you notice about\n"
            "real ants that's like\n"
            "SimAnt? What's different?\n"
            "WARNING: Ants aren't good\n"
            "pets. They don't like\n"
            "to be petted. They don't\n"
            "chase away burglars. They\n"
            "don't fetch or play games.\n"
            "And your Mom will get mad\n"
            "if you bring them into the\n"
            "house."
        ,
    },
};

/* Convenience: text-only pointer array for callers that want strings. */
static const char *const encyclopedia_pages[30] = {
    encyclopedia_pages_full[0].text,
    encyclopedia_pages_full[1].text,
    encyclopedia_pages_full[2].text,
    encyclopedia_pages_full[3].text,
    encyclopedia_pages_full[4].text,
    encyclopedia_pages_full[5].text,
    encyclopedia_pages_full[6].text,
    encyclopedia_pages_full[7].text,
    encyclopedia_pages_full[8].text,
    encyclopedia_pages_full[9].text,
    encyclopedia_pages_full[10].text,
    encyclopedia_pages_full[11].text,
    encyclopedia_pages_full[12].text,
    encyclopedia_pages_full[13].text,
    encyclopedia_pages_full[14].text,
    encyclopedia_pages_full[15].text,
    encyclopedia_pages_full[16].text,
    encyclopedia_pages_full[17].text,
    encyclopedia_pages_full[18].text,
    encyclopedia_pages_full[19].text,
    encyclopedia_pages_full[20].text,
    encyclopedia_pages_full[21].text,
    encyclopedia_pages_full[22].text,
    encyclopedia_pages_full[23].text,
    encyclopedia_pages_full[24].text,
    encyclopedia_pages_full[25].text,
    encyclopedia_pages_full[26].text,
    encyclopedia_pages_full[27].text,
    encyclopedia_pages_full[28].text,
    encyclopedia_pages_full[29].text,
};

/* ============================================================
 * TUTORIAL — 54 messages, pointers at $00:E2C2 → bank $01
 * ============================================================ */

static const char *const tutorial_messages[54] = {
    /*  0  $01:B27F  (179 bytes) */
    "Welcome to SimAnt!\n"
    "Follow the instructions\n"
    "on the screen to learn\n"
    "how to be a proper bug.\n"
    "\n"
    "NOTE: (left) and (right)\n"
    "refer to mouse buttons.\n"
    "Ignore them if you\n"
    "don't have a mouse."
    ,
    /*  1  $01:B332  (103 bytes) */
    "In SimAnt, you lead,\n"
    "teach and control\n"
    "your colony by control-\n"
    "ling the Yellow Ant.\n"
    "Let's learn how..."
    ,
    /*  2  $01:B399  (130 bytes) */
    "Right now, the Yellow\n"
    "Ant is underground.\n"
    "\n"
    "Place the hand cursor\n"
    "on a spot where there\n"
    "is no tunnel and press\n"
    "the A(left) button."
    ,
    /*  3  $01:B41B  (48 bytes) */
    "Did you dig it?\n"
    "Go ahead and dig\n"
    "a little more."
    ,
    /*  4  $01:B44B  (129 bytes) */
    "Let's see what's up...\n"
    "on the surface. Place\n"
    "the hand on the nest\n"
    "exit near the top of\n"
    "the screen, and press\n"
    "the A(left) button."
    ,
    /*  5  $01:B4CC  (35 bytes) */
    "This is a close-up\n"
    "of the surface."
    ,
    /*  6  $01:B4EF  (103 bytes) */
    "To make the Yellow Ant\n"
    "walk, place the hand\n"
    "where you want the ant\n"
    "to go and press the\n"
    "A(left) button."
    ,
    /*  7  $01:B556  (99 bytes) */
    "One of the most\n"
    "important things the\n"
    "Yellow Ant does is find\n"
    "food for the colony.\n"
    "Let's find some."
    ,
    /*  8  $01:B5B9  (99 bytes) */
    "Select the top icon\n"
    "on the left side of\n"
    "the screen.\n"
    "Then select\n"
    "Surface Overview\n"
    "from the submenu."
    ,
    /*  9  $01:B61C  (151 bytes) */
    "This is the surface\n"
    "overview. The green\n"
    "dots are food.\n"
    "The yellow dot \n"
    "is the Yellow Ant. The\n"
    "red square outlines the\n"
    "area shown in the\n"
    "Close-up view."
    ,
    /* 10  $01:B6B3  (96 bytes) */
    "Place the hand on the\n"
    "food and press the\n"
    "A(left) button.\n"
    "\n"
    "The red square will\n"
    "move to the food."
    ,
    /* 11  $01:B713  (103 bytes) */
    "Select the icon in\n"
    "the upper-left\n"
    "corner of the screen,\n"
    "then select\n"
    "Surface Close-up\n"
    "from the submenu."
    ,
    /* 12  $01:B77A  (129 bytes) */
    "We're back in Close-up\n"
    "view. Place the hand\n"
    "on some food and press\n"
    "the A(left) button. The\n"
    "Yellow Ant will walk\n"
    "toward the food."
    ,
    /* 13  $01:B7FB  (101 bytes) */
    "By now the Yellow Ant\n"
    "is probably hungry.\n"
    "Place the hand on some\n"
    "food and press the\n"
    "B(right) button."
    ,
    /* 14  $01:B860  (127 bytes) */
    "The Yellow Ant ate and\n"
    "regained its strength.\n"
    "Always keep an eye on\n"
    "the strength gauge in\n"
    "the lower-left corner\n"
    "of the screen."
    ,
    /* 15  $01:B8DF  (101 bytes) */
    "Let's bring some food\n"
    "back to the nest.\n"
    "\n"
    "Place the hand on \n"
    "some food and press\n"
    "the B(right) button."
    ,
    /* 16  $01:B944  (79 bytes) */
    "This time the Yellow\n"
    "Ant picked up the food.\n"
    "It will only eat when\n"
    "it is weak."
    ,
    /* 17  $01:B993  (85 bytes) */
    "To take the food back\n"
    "to the nest, move the\n"
    "hand to the nest\n"
    "entrance, to your left."
    ,
    /* 18  $01:B9E8  (91 bytes) */
    "When you find the nest\n"
    "place the hand over the\n"
    "hole and press the\n"
    "A(left) button to\n"
    "enter."
    ,
    /* 19  $01:BA43  (99 bytes) */
    "Once inside the nest,\n"
    "place the hand where\n"
    "you want to put the food\n"
    "and press the B(right)\n"
    "button."
    ,
    /* 20  $01:BAA6  (60 bytes) */
    "Now let's go back to\n"
    "the surface and try a\n"
    "few more things."
    ,
    /* 21  $01:BAE2  (114 bytes) */
    "Find a small pebble.\n"
    "Place the hand on it,\n"
    "then press the B(left)\n"
    "button.\n"
    "The Yellow Ant will\n"
    "pick up the pebble."
    ,
    /* 22  $01:BB54  (97 bytes) */
    "To put the pebble down,\n"
    "place the hand where\n"
    "you want to put it,\n"
    "then press the B(right)\n"
    "button."
    ,
    /* 23  $01:BBB5  (94 bytes) */
    "You can use pebbles to\n"
    "build protective walls\n"
    "and block entrances to\n"
    "nests or ant lion\n"
    "holes."
    ,
    /* 24  $01:BC13  (106 bytes) */
    "Now place the hand\n"
    "over the Yellow Ant\n"
    "and press the B(right)\n"
    "button. Select\n"
    "Recruit 10 from the\n"
    "submenu."
    ,
    /* 25  $01:BC7D  (80 bytes) */
    "Ten black ants will\n"
    "rush to the Yellow\n"
    "Ant's side, ready to\n"
    "follow it anywhere."
    ,
    /* 26  $01:BCCD  (59 bytes) */
    "Move the Yellow Ant\n"
    "around, to see that\n"
    "the others follow."
    ,
    /* 27  $01:BD08  (73 bytes) */
    "Select the top icon from\n"
    "the menu again and go\n"
    "back to\n"
    "Surface Overview."
    ,
    /* 28  $01:BD51  (75 bytes) */
    "Next, select the fifth\n"
    "icon from the left.\n"
    "\n"
    "Select House from\n"
    "the submenu."
    ,
    /* 29  $01:BD9C  (84 bytes) */
    "The flashing square is\n"
    "the part of the garden\n"
    "that you saw in the\n"
    "Surface overview."
    ,
    /* 30  $01:BDF0  (86 bytes) */
    "Each of the squares is\n"
    "another land to conquer,\n"
    "another place to\n"
    "battle the red ants."
    ,
    /* 31  $01:BE46  (115 bytes) */
    "Place the hand on the\n"
    "leftmost icon at the top\n"
    "of the screen and press\n"
    "the A(left) button to\n"
    "see inside the house."
    ,
    /* 32  $01:BEB9  (300 bytes) */
    "In a Full Game your goal\n"
    "is to defeat the red\n"
    "ants in each section of\n"
    "the yard and drive the\n"
    "humans out of the house.\n"
    "To expand into new\n"
    "areas, you must build up\n"
    "a black ant population\n"
    "of 100, with 20 winged\n"
    "ants.\n"
    "The winged ants will go\n"
    "on a mating flight and\n"
    "the new queens will land\n"
    "in new areas."
    ,
    /* 33  $01:BFE5  (52 bytes) */
    "Let's go back to the\n"
    "surface. Select the\n"
    "Exit icon."
    ,
    /* 34  $01:C019  (62 bytes) */
    "Besides leading, there\n"
    "are other ways to con-\n"
    "trol your ants."
    ,
    /* 35  $01:C057  (77 bytes) */
    "Select the third icon\n"
    "from the left, then \n"
    "select Behavior from\n"
    "the submenu."
    ,
    /* 36  $01:C0A4  (148 bytes) */
    "This is the Behavior\n"
    "Control Panel.  Here you\n"
    "can control the types\n"
    "of jobs your ants do.\n"
    "Select the icon that\n"
    "says Manual with the\n"
    "A(left) button."
    ,
    /* 37  $01:C138  (165 bytes) */
    "Now place the hand on\n"
    "the cross inside the\n"
    "triangle. Press the\n"
    "A(left) button and move\n"
    "the cross.\n"
    "\n"
    "Notice that the number\n"
    "of ants doing each job\n"
    "(behavior) changes."
    ,
    /* 38  $01:C1DD  (124 bytes) */
    "Selecting the Auto icon\n"
    "puts Behavior in Auto-\n"
    "matic mode. It will\n"
    "adjust the behaviors for\n"
    "you depending on the\n"
    "situation."
    ,
    /* 39  $01:C259  (67 bytes) */
    "Selecting the Manual\n"
    "icon lets you adjust\n"
    "your own ants'\n"
    "behavior."
    ,
    /* 40  $01:C29C  (48 bytes) */
    "Let's return to the\n"
    "game. Select the Exit\n"
    "icon."
    ,
    /* 41  $01:C2CC  (69 bytes) */
    "You can also control\n"
    "what types of ants\n"
    "will be born in your\n"
    "colony."
    ,
    /* 42  $01:C311  (73 bytes) */
    "Select the third icon\n"
    "from the left, then\n"
    "select Caste from the\n"
    "submenu."
    ,
    /* 43  $01:C35A  (134 bytes) */
    "This is the Caste\n"
    "Control Panel. Here you\n"
    "can control how many of\n"
    "the ants born in your\n"
    "colony will be workers,\n"
    "soldiers or breeders."
    ,
    /* 44  $01:C3E0  (69 bytes) */
    "This control panel works\n"
    "the same way as the\n"
    "Behavior Control Panel."
    ,
    /* 45  $01:C425  (35 bytes) */
    "Select Exit to return\n"
    "to the game."
    ,
    /* 46  $01:C448  (101 bytes) */
    "Select the icon in the\n"
    "top-left corner of the\n"
    "screen, then select\n"
    "Surface Close-up from\n"
    "the submenu."
    ,
    /* 47  $01:C4AD  (41 bytes) */
    "Let's try an attack on\n"
    "the red ant nest."
    ,
    /* 48  $01:C4D6  (139 bytes) */
    "Place the hand over the\n"
    "Yellow Ant and press the\n"
    "B(right) button. Select\n"
    "Recruit 10 from the\n"
    "submenu. Do it again.\n"
    "Do it three more times."
    ,
    /* 49  $01:C561  (89 bytes) */
    "You have just recruited\n"
    "an army of 50 obedient\n"
    "black ants, ready to\n"
    "follow you anywhere."
    ,
    /* 50  $01:C5BA  (182 bytes) */
    "Move the Yellow Ant\n"
    "toward the red ant\n"
    "nest. The red ants will\n"
    "attack as you approach.\n"
    "Remember, the Yellow Ant\n"
    "is the general--let the\n"
    "workers and soldiers do\n"
    "most of the fighting."
    ,
    /* 51  $01:C670  (46 bytes) */
    "You have located the\n"
    "red ants' nest.\n"
    "Attack!!"
    ,
    /* 52  $01:C69E  (75 bytes) */
    "Your attack didn't\n"
    "succeed this time, but\n"
    "you'll have another\n"
    "chance soon."
    ,
    /* 53  $01:C6E9  (143 bytes) */
    "This is the end of the\n"
    "SimAnt Tutorial.\n"
    "\n"
    "If you missed anything,\n"
    "you can repeat it, or\n"
    "read the manual.\n"
    "\n"
    "We hope you enjoy your\n"
    "life as a bug!"
    ,
};

/* ============================================================
 * SHORT PROMPTS — referenced by player_actions.c / scenarios.c /
 * text_screens.c.  Each entry is a label + the literal English
 * string ($FF-terminated in ROM, $FE → '\n' here).
 * ============================================================ */

typedef struct {
    const char *label;
    uint8_t     bank;
    uint16_t    addr;
    const char *text;
} ShortPrompt;

static const ShortPrompt short_prompts[19] = {
    { "yellow_ant_fed_by_nestmate", 0x01, 0xA215,
      "The Yellow Ant\nwas fed by its\nnestmate" },  /* 39 bytes raw */
    { "yellow_ant_ate_regained", 0x01, 0xB860,
      "The Yellow Ant ate and\nregained its strength.\nAlways keep an eye on\nthe strength gauge in\nthe lower-left corner\nof the screen." },  /* 127 bytes raw */
    { "will_pick_up_pebble", 0x01, 0xBAE2,
      "Find a small pebble.\nPlace the hand on it,\nthen press the B(left)\nbutton.\nThe Yellow Ant will\npick up the pebble." },  /* 114 bytes raw */
    { "yellow_ant_died_last_life", 0x01, 0xA351,
      "The Yellow Ant has\njust lost its last\nlife.\nThis game is over." },  /* 63 bytes raw */
    { "walk_toward_food", 0x01, 0xB77A,
      "We're back in Close-up\nview. Place the hand\non some food and press\nthe A(left) button. The\nYellow Ant will walk\ntoward the food." },  /* 129 bytes raw */
    { "recruit_5", 0x01, 0x86F3,
      "Recruit 5  " },  /* 12 bytes raw */
    { "recruit_10", 0x01, 0x86FF,
      "Recruit 10 " },  /* 12 bytes raw */
    { "recruit_all", 0x01, 0x870B,
      "Recruit All" },  /* 12 bytes raw */
    { "release_half", 0x01, 0x8717,
      "Release 1/2" },  /* 12 bytes raw */
    { "release_all", 0x01, 0x8723,
      "Release All" },  /* 12 bytes raw */
    { "dig_new_nest", 0x01, 0x8734,
      "Dig New Nest" },  /* 13 bytes raw */
    { "lay_eggs", 0x01, 0x8741,
      "Lay Eggs" },  /* 9 bytes raw */
    { "topic_blank_filler", 0x01, 0x89E7,
      "                 " },  /* 18 bytes raw */
    { "topic_introduction", 0x01, 0x89F9,
      "  Introduction   " },  /* 18 bytes raw */
    { "topic_ant_life", 0x01, 0x8A0B,
      "  Ant Life       " },  /* 18 bytes raw */
    { "topic_ants_at_home", 0x01, 0x8A1D,
      "  Ants at Home   " },  /* 18 bytes raw */
    { "topic_ants_relatives", 0x01, 0x8A2F,
      "  Ants&Relatives " },  /* 18 bytes raw */
    { "topic_simant_strategy", 0x01, 0x8A41,
      "  SimAnt Strategy" },  /* 18 bytes raw */
    { "topic_exit", 0x01, 0x8A53,
      "  EXIT           " },  /* 18 bytes raw */
};

/* ============================================================
 * STATUS-MESSAGE BLOB at $01:B07A
 *   9 × 32-byte space-padded fixed-width strings, NO $FE/$FF
 *   inside (one $FF after the trailing 'PAUSE' entry).  These
 *   are indexed by ID for one-line on-screen alerts.
 * ============================================================ */

typedef struct {
    const char *label;
    const char *text;
} StatusMessage;

static const StatusMessage status_messages[9] = {
    { "is_hungry", "The Yellow Ant is HUNGRY!!!" },
    { "colony_needs_more_food", "The colony needs more food!" },
    { "nest_too_crowded_dig", "The nest is too crowded! Dig!" },
    { "red_ants_attacking", "The red ants are attacking!" },
    { "feed_queen_hungry", "Feed the queen! She's hungry." },
    { "human_coming_hide", "Yuck! A human is coming! Hide!" },
    { "press_B_dig_new_nest", "Press B and select Dig New Nest." },
    { "press_B_lay_eggs", "Press B and select Lay Eggs." },
    { "pause", "PAUSE" },
};

/* Keep symbols reachable for static analysis. */
__attribute__((used))
static const void * const _text_content_doc_refs[] = {
    (void const *)encyclopedia_pages,
    (void const *)tutorial_messages,
    (void const *)short_prompts,
    (void const *)status_messages,
    (void const *)encyclopedia_pages_full,
};
